version: 0.1.0+{build}

image: Visual Studio 2017

install:
  - cinst elixir
  - SET PATH=C:\ProgramData\chocolatey\lib\Elixir\bin;%PATH%

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - mix test

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  